update=Sun 20 Jan 2019 07:55:55 PM EET
last_client=kicad
[eeschema]
version=1
LibDir=
[eeschema/libraries]
LibName1=expansion-cache
LibName2=oric-expansion
[general]
version=1
[schematic_editor]
version=1
PageLayoutDescrFile=
PlotDirectoryName=
SubpartIdSeparator=0
SubpartFirstId=65
NetFmtName=
SpiceForceRefPrefix=0
SpiceUseNetNumbers=0
LabSize=60
